---
- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False
  become: yes


- name: Installing openjdk
  yum:
    name: "{{ openjdk_package_name }}"
    state: latest
    update_cache: yes
  become: yes
